<p>Throwing an exception during startup or shutdown results in an implementation-defined termination of the program. This is because there is no where to put &lt;code&gt;try&lt;/code&gt;/&lt;code&gt;catch&lt;/code&gt; blocks to catch exceptions thrown in the startup phase, when static objects are being constructed, or during the shutdown phase, when those static objects are being destroyed.</p>
<p>Therefore exceptions should not be thrown during the construction or destruction of static objects.</p>
<h2>Noncompliant Code Example</h2>
<pre>
class C
{

  public:
    C ( )
    {
      throw ( 0 ); // Noncompliant; thrown before main starts
    }
    ~C ( )
    {
      throw ( 0 ); // Noncompliant; thrown after main exits
    }
};

C c; // An exception thrown in C's constructor or destructor will
     // cause the program to terminate, and will not be caught by
     // the handler in main

int main( ... )
{
  // ...
</pre>
<h2>See</h2>
<ul>
<li>MISRA C++:2008, 15-3-1</li>
</ul>
