When a constructor/destructor has a function-try-block, the code inside of the catch clause will be executed after the object has been destroyed (if the object was partially constructed when the exception was thrown, this part will be destroyed before going in the catch block). Therefore, the members of the object are not available, and it is undefined behavior to access them.

Since the lifetime of a static member is greater than that of the object itself, so static member can be accessed from the catch code.


== Noncompliant Code Example

----
class A
{
public:
  int i;
  C ( )
  try
  {
    // Action that may raise an exception
  }
  catch ( ... )
  {
    if ( i == 0 ) // Noncompliant, i has ben destroyed
    {
      // ...
    }
  }
  ~C ( )
  try
  {
    // Action that may raise an exception
  }
  catch ( ... )
  {
    if ( i == 0 ) // Noncompliant
    {
    }
  }
};
----


== See

* MISRA C++:2008, 15-3-3
* https://www.securecoding.cert.org/confluence/x/6wDOAQ[CERT, ERR53-CPP.] - Do not reference base classes or class data members in a constructor or destructor function-try-block handler


