Throwing an exception from a destructor results in undefined behavior, meaning that your program could be terminated abruptly without neatly destroying others objects.

Thus destructors should never <code>throw</code> exceptions. Instead, they should catch and handle those thrown by the functions they call, and be <code>noexcept</code>.

This rule raises an issue when a destructor is not <code>noexcept</code>. By default, destructors are <code>noexcept</code>, therefore most of the time, nothing needs to be written in the source code. A destructor is not <code>noexcept</code> if:
* the base class or a data member has a non <code>noexcept</code> destructor,
* the destructor is decorated with the <code>noexcept</code> keyword followed by something that evaluates to false.


== Noncompliant Code Example

----
struct A {
  ~A() noexcept(false) {} // Noncompliant
};

struct C {
  /* ... */
  A a; // This member data prevents automatic declaration of the destructor as noexcept
  ~C() { // Noncompliant
    /* ... */
  }
};
----


== Compliant Solution

----
struct A {
  ~A() noexcept(true) {}
};

struct C {
  /* ... */
  A a;
  ~C() { // Compliant, noexcept by default
    /* ... */
  }
};
----


== See

* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c36-a-destructor-may-not-fail[C++ Core Guidelines C.36] A destructor may not fail
* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c37-make-destructors-noexcept[C++ Core Guidelines C.37] Make destructors noexcept

